artifacts_config:
  save_artifacts_to: /home/sei/tetrahedron_pair_ML/artifacts
evaluator_config:
  evaluation_n_bins: 10
  model_path: /artifacts/id-20250408-065815_deepset_regression_100000-train_100000-val_vol-0-0.01_epochs-5_adamw-0.001_distributions-polyhedron_intersection-100/model.pt
  regression_consistency_thresholds:
    atol: 0.0001
    rtol: 0.1
  skip_evaluation: false
  task: IntersectionStatus
  test_data_path: /home/sei/tetrahedron_pair_ML/src/evaluator/test_data
  transformations: &id001 []
  volume_range: &id002
  - 0
  - 0.02
home: /home/sei/tetrahedron_pair_ML
model_config:
  activation_function: relu
  architecture:
    mlp:
      classification_head:
      - 128
      - 1
      regression_head: []
      shared_layers:
      - 128
      - 128
    tetrahedronpairnet:
      classification_head:
      - 12
      - 6
      - 3
      - 2
      - 1
      per_tetrahedron_layers:
      - 12
      - 12
      per_two_tetrahedra_layers:
      - 12
      - 12
      per_vertex_layers:
      - 12
      - 12
      regression_head:
      - 12
      - 12
      - 12
      - 1
      shared_layers:
      - 12
      - 12
      tetrahedra_aggregation_function: max
      vertices_aggregation_function: max
    use_model: mlp
  common_parameters:
    activation_function: relu
    dropout_rate: 0.1
    task: IntersectionStatus
    volume_scale_factor: 1
  dropout_rate: 0.1
  processed_data_path: data/processed
  skip_building: false
  task: IntersectionStatus
processor_config:
  augmentations:
    point_wise_permutation_augmentation_pct: 0
    tetrahedron_wise_permutation_augmentation_pct: 0
    x_sorting:
      spatial_based: null
      volume_based: null
    y_sorting:
      difficulty_based: null
  dataset_paths:
    processed_data: /home/sei/tetrahedron_pair_ML/data/processed
    raw_data: /home/sei/tetrahedron_pair_ML/data/raw
  intersection_distributions:
    no_intersection: 50
    point_intersection: 4
    polygon_intersection: 23
    polyhedron_intersection: 18
    segment_intersection: 5
  num_train_samples: 100000
  num_val_samples: 100000
  number_of_bins: 100
  skip_processing: false
  transformations: *id001
  volume_range: *id002
  volume_scale_factor: 1
trainer_config:
  batch_size: 32
  epochs: 20
  fine_tune_data_path: /home/sei/tetrahedron_pair_ML/data/raw/scenes/scene1_two_random_tetrahedra_colliding.csv
  fine_tune_model_path: /home/sei/tetrahedron_pair_ML/artifacts/id0605203440_tetrahedronpairnet_IntersectionStatus_IntersectionVolume_1000000-train_10000-val_vol-0-0.02_epochs-20_adamw-0.001_distributions-no_intersection-43_point_intersection-3_segment_intersection-5_polygon_intersection-22_polyhedron_intersection-27/model.pt
  fine_tune_on: false
  learning_rate: 0.001
  loss_function: IntersectionStatus
  optimizer: adamw
  processed_data_path: data/processed
  skip_training: false
