processor_config:
  dataset_paths:
    raw_data: /home/sei/tetrahedron_pair_ML/data/raw
    processed_data: &processed_data_path /home/sei/tetrahedron_pair_ML/data/processed

  num_train_samples: 20000
  num_val_samples: 20000

  intersection_distributions:
    # Note: Percentages are approximate and should sum to ~100%. 
    no_intersection: 50
    point_intersection: 0
    segment_intersection: 0
    polygon_intersection: 0
    polyhedron_intersection: 50

  volume_range: [0, 0.01]
  number_of_bins: 1000 # Granualatiry of volumes

  augmentations:
    sort: null # null, X (sort by X coordinate), SFC (sort by space filling curves)
    larger_tetrahedron_first: false

    # Note: Augmentation percentages should sum at most to 0.5
    vertex_permutation_augmentation_pct: 0
    tetrahedron_permutation_augmentation_pct: 0
    rigid_transformation_augmentation_pct: 0
    affine_linear_transformation_augmentation_pct: 0

model_config:
  architecture: mlp # mlp, deep_set
  activation_function: relu
  dropout_rate: 0.0
  task: &task_type binary_classification # binary_classification, Regression, Classification&Regression

trainer_config:
  type: normal_training # normal_training, contrastive_learning

  processed_data_path: *processed_data_path

  normal_training:
    loss_function: *task_type
    evaluation_metric: accuracy
    optimizer: adam # adam, adamw, sgd
    learning_rate: 0.001
    epochs: 20
    batch_size: 32
    learning_rate_schedule: null
    early_stopping_patience: 10

  # contrastive_learning:
  #   loss_function: cosine_similarity
  #   evaluation_metric: contrastive_accuracy
  #   optimizer: adam
  #   margin: 0.001
  #   learning_rate: 0.001
  #   epochs: 20
  #   batch_size: 32
  #   learning_rate_schedule: null

artifacts_config:
  save_artifacts_to: /home/sei/tetrahedron_pair_ML/artifacts
