home: &home_path /home/sei/tetrahedron_pair_ML # all other paths are relative to home

artifacts_config:
  save_artifacts_to: artifacts 

processor_config:
  skip_processing: false
  dataset_paths:
    raw_data: data/raw          
    processed_data: &processed_data_path data/processed

  num_train_samples: 20000
  num_val_samples: 20000

  volume_scale_factor: &volume_scale_factor 10000

  intersection_distributions:
    # Note: Percentages are approximate and should sum to ~100%. 
    no_intersection: 0
    point_intersection: 0
    segment_intersection: 0
    polygon_intersection: 0
    polyhedron_intersection: 100

  volume_range: [0, 0.01]
  number_of_bins: 100

  augmentations: &augmentations_config
    sort: null
    larger_tetrahedron_first: false

    # Note: Augmentation percentages should sum at most to 50
    point_wise_permutation_augmentation_pct: 0
    tetrahedron_wise_permutation_augmentation_pct: 0

  transformations: &transformations_config
    affine_linear_transformation: false

model_config:

  skip_building: false
  task: &task_type regression # binary_classification, regression, classification_and_regression
  activation_function: relu
  dropout_rate: 0.0
  processed_data_path: *processed_data_path
  volume_scale_factor: *volume_scale_factor

  architecture:
    use: mlp # mlp, deep_set

    mlp:
      shared_layers: [1024]
      classification_head: []
      regression_head: [1]

    deep_set:
      num_residual_blocks_per_tet: 1
      num_residual_blocks_post_concat: 1
      classification_head: []
      regression_head: []

trainer_config:
  skip_training: false
  processed_data_path: *processed_data_path

  loss_function: *task_type
  evaluation_metric: accuracy
  optimizer: adamw # adam, adamw, sgd
  learning_rate: 0.001
  epochs: 5
  batch_size: 32
  learning_rate_schedule: null
  early_stopping_patience: 10

evaluator_config:
  skip_evaluation: false
  task: *task_type
  test_data_path: src/evaluator/test_data 
  augmentations: *augmentations_config
  transformations: *transformations_config
