artifacts_config:
  save_artifacts_to: /home/erendiro/repos/tetrahedron_pair_ML/artifacts

processor_config:
  skip_processing: false
  dataset_paths:
    raw_data: /home/erendiro/repos/tetrahedron_pair_ML/data/raw
    processed_data: &processed_data_path /home/erendiro/repos/tetrahedron_pair_ML/data/processed

  num_train_samples: 10000
  num_val_samples: 10000

  intersection_distributions:
    # Note: Percentages are approximate and should sum to ~100%. 
    no_intersection: 50
    point_intersection: 1
    segment_intersection: 1
    polygon_intersection: 1
    polyhedron_intersection: 47

  volume_range: [0, 0.01]
  number_of_bins: 1000 # Granualatiry of volumes

  augmentations:
    sort: null # null, X (sort by X coordinate), SFC (sort by space filling curves)
    larger_tetrahedron_first: false

    # Note: Augmentation percentages should sum at most to 0.5
    vertex_permutation_augmentation_pct: 0
    tetrahedron_permutation_augmentation_pct: 0

    # Note: transformations are applied to all training and validation samples
    rigid_transformation: false
    affine_linear_transformation: false

model_config:
  skip_building: false
  architecture: mlp # mlp, deep_set
  activation_function: relu # relu, tanh, leaky_relu, elu
  dropout_rate: 0.0
  task: &task_type binary_classification # binary_classification, regression, classification_and_regression

trainer_config:
  skip_training: false
  processed_data_path: *processed_data_path

  loss_function: *task_type
  evaluation_metric: accuracy
  optimizer: adamw # adam, adamw, sgd
  learning_rate: 0.001
  epochs: 5
  batch_size: 32
  learning_rate_schedule: null
  early_stopping_patience: 10

evaluator_config:
  skip_evaluation: false
  task: *task_type
  test_data_path: /home/erendiro/repos/tetrahedron_pair_ML/src/evaluator/test_data
