processor_config:
  dataset_paths:
    raw_data: /home/sei/tetrahedron_pair_ML/data/raw
    processed_data: &processed_data_path /home/sei/tetrahedron_pair_ML/data/processed

  num_train_samples: 10000
  num_val_samples: 10000

  intersection_distributions:
    # Note: Percentages are approximate and should sum to ~100%. 
    no_intersection: 50
    point_intersection: 50
    segment_intersection: 0
    polygon_intersection: 0
    polyhedron_intersection: 0

  volume_range: [0, 0.01]
  number_of_bins: 100 # Granualatiry of volumes

  augmentations:
    sort: null # null, X (sort by X coordinate), SFC (sort by space filling curves)
    larger_tetrahedron_first: false

    # Note: Augmentation percentages should sum at most to 0.5
    vertex_permutation_augmentation_pct: 0
    tetrahedron_permutation_augmentation_pct: 0
    rigid_transformation_augmentation_pct: 0
    affine_linear_transformation_augmentation_pct: 0

model_config:
  encoder_config:
    type: mlp # deep_set, mlp
    activation_function: relu
    dropout_rate: 0.0
    weight_decay: 0.0

  decoder_config:
    type: mlp
    activation_function: relu      
    task: classification # Classification, Regression, Classification&Regression

trainer_config:
  type: normal_training # normal_training, contrastive_learning

  processed_data_path: *processed_data_path

  normal_training:
    loss_function: binary_crossentropy
    evaluation_metric: accuracy
    optimizer: adam
    learning_rate: 0.001
    epochs: 20
    batch_size: 32
    learning_rate_schedule: null

  # contrastive_learning:
  #   loss_function: cosine_similarity
  #   evaluation_metric: contrastive_accuracy
  #   optimizer: adam
  #   margin: 0.001
  #   learning_rate: 0.001
  #   epochs: 20
  #   batch_size: 32
  #   learning_rate_schedule: null

artifacts_config:
  save_artifacts_to: /home/sei/tetrahedron_pair_ML/artifacts
