artifacts_config:
  save_artifacts_to: /home/sei/tetrahedron_pair_ML/artifacts
evaluator_config:
  augmentations: &id001
    point_wise_permutation_augmentation_pct: 10
    sort: null
    tetrahedron_wise_permutation_augmentation_pct: 0
    volume_sorting: null
  evaluation_n_bins: 10
  model_path: /home/sei/tetrahedron_pair_ML/artifacts/id-20250408-065815_deepset_regression_100000-train_100000-val_vol-0-0.01_epochs-5_adamw-0.001_distributions-polyhedron_intersection-100/model.pt
  skip_evaluation: false
  task: IntersectionStatus_IntersectionVolume
  test_data_path: /home/sei/tetrahedron_pair_ML/src/evaluator/test_data
  transformations: &id002
  - unitary_tetrahedron_transformation
  volume_range: &id003
  - 0
  - 0.01
home: /home/sei/tetrahedron_pair_ML
model_config:
  architecture:
    mlp:
      classification_head:
      - 24
      - 24
      - 12
      - 6
      - 3
      - 2
      - 1
      regression_head:
      - 24
      - 24
      - 24
      - 24
      - 1
      shared_layers:
      - 48
      - 48
      - 48
      - 48
      - 48
    tetrahedronpairnet:
      classification_head:
      - 12
      - 6
      - 3
      - 2
      - 1
      per_tetrahedron_layers:
      - 48
      - 48
      - 48
      per_two_tetrahedra_layers:
      - 48
      - 48
      - 48
      per_vertex_layers:
      - 12
      - 12
      - 12
      regression_head:
      - 48
      - 48
      - 48
      - 1
      residual: true
      shared_layers:
      - 48
      - 48
      - 48
      tetrahedra_aggregation_function: max
      vertices_aggregation_function: max
    use_model: tetrahedronpairnet
  common_parameters:
    activation_function: relu
    dropout_rate: 0.2
    task: IntersectionStatus_IntersectionVolume
    volume_scale_factor: 1000000
  processed_data_path: data/processed
  skip_building: false
processor_config:
  augmentations: *id001
  dataset_paths:
    processed_data: /home/sei/tetrahedron_pair_ML/data/processed
    raw_data: /home/sei/tetrahedron_pair_ML/data/raw
  intersection_distributions:
    no_intersection: 43
    point_intersection: 3
    polygon_intersection: 22
    polyhedron_intersection: 27
    segment_intersection: 5
  num_train_samples: 800000
  num_val_samples: 8000
  number_of_bins: 200
  skip_processing: true
  transformations: *id002
  volume_range: *id003
  volume_scale_factor: 1000000
trainer_config:
  batch_size: 32
  epochs: 20
  learning_rate: 0.001
  loss_function: IntersectionStatus_IntersectionVolume
  optimizer: adamw
  processed_data_path: data/processed
  skip_training: false
