artifacts_config:
  save_artifacts_to: /home/sei/tetrahedron_pair_ML/artifacts
evaluator_config:
  augmentations: &id001
    point_wise_permutation_augmentation_pct: 0
    sort: null
    tetrahedron_wise_permutation_augmentation_pct: 0
    volume_sorting: null
  model_path: /home/sei/tetrahedron_pair_ML/artifacts/id-20250408-065815_deepset_regression_100000-train_100000-val_vol-0-0.01_epochs-5_adamw-0.001_distributions-polyhedron_intersection-100/model.pt
  skip_evaluation: false
  task: binary_classification
  test_data_path: /home/sei/tetrahedron_pair_ML/src/evaluator/test_data
  transformations: rigid_transformation
home: /home/sei/tetrahedron_pair_ML
model_config:
  activation_function: relu
  architecture:
    deepset:
      classification_head:
      - 12
      - 6
      - 1
      hidden_dim: 12
      num_blocks: 2
      output_dim: 12
      regression_head: []
    mlp:
      classification_head:
      - 24
      - 6
      - 1
      regression_head: []
      shared_layers:
      - 24
      - 24
    tpnet:
      classification_head:
      - 12
      - 12
      - 12
      - 1
      per_tet_layers:
      - 12
      - 12
      regression_head: []
      shared_layers:
      - 12
      - 12
    use: mlp
  dropout_rate: 0.0
  processed_data_path: data/processed
  skip_building: false
  task: binary_classification
  volume_scale_factor: 1000000
processor_config:
  augmentations: *id001
  dataset_paths:
    processed_data: /home/sei/tetrahedron_pair_ML/data/processed
    raw_data: /home/sei/tetrahedron_pair_ML/data/raw
  intersection_distributions:
    no_intersection: 43
    point_intersection: 3
    polygon_intersection: 22
    polyhedron_intersection: 27
    segment_intersection: 5
  num_train_samples: 100000
  num_val_samples: 50000
  number_of_bins: 100
  skip_processing: false
  transformations: rigid_transformation
  volume_range:
  - 0
  - 0.01
  volume_scale_factor: 1000000
trainer_config:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  loss_function: binary_classification
  optimizer: adamw
  processed_data_path: data/processed
  skip_training: false
