artifacts_config:
  save_artifacts_to: /home/sei/tetrahedron_pair_ML/artifacts
evaluator_config:
  augmentations: &id001
    point_wise_permutation_augmentation_pct: 0
    tetrahedron_wise_permutation_augmentation_pct: 0
    x_sorting:
      spatial_based: null
      volume_based: null
    y_sorting:
      difficulty_based: null
  evaluation_n_bins: 10
  model_path: /home/sei/tetrahedron_pair_ML/artifacts/id-20250408-065815_deepset_regression_100000-train_100000-val_vol-0-0.01_epochs-5_adamw-0.001_distributions-polyhedron_intersection-100/model.pt
  regression_consistency_thresholds:
    atol: 0.0001
    rtol: 0.1
  skip_evaluation: false
  task: IntersectionStatus_IntersectionVolume
  test_data_path: /home/sei/tetrahedron_pair_ML/src/evaluator/test_data
  transformations: &id002 []
  volume_range:
  - 0
  - 0.01666666667
home: /home/sei/tetrahedron_pair_ML
model_config:
  architecture:
    mlp:
      classification_head:
      - 128
      - 128
      - 1
      regression_head:
      - 128
      - 128
      - 1
      shared_layers:
      - 128
    tetrahedronpairnet:
      classification_head:
      - 16
      - 1
      per_tetrahedron_layers:
      - 64
      - 64
      per_two_tetrahedra_layers:
      - 32
      per_vertex_layers:
      - 48
      - 48
      - 48
      regression_head:
      - 16
      - 1
      shared_layers:
      - 256
      tetrahedra_aggregation_function: max
      vertices_aggregation_function: max
    use_model: tetrahedronpairnet
  common_parameters:
    activation_function: relu
    dropout_rate: 0.1
    task: IntersectionStatus_IntersectionVolume
    volume_scale_factor: 1000
  processed_data_path: data/processed
  skip_building: false
  task: IntersectionStatus_IntersectionVolume
  use_model: tetrahedronpairnet
processor_config:
  augmentations: *id001
  dataset_paths:
    processed_data: /home/sei/tetrahedron_pair_ML/data/processed
    raw_data: /home/sei/tetrahedron_pair_ML/data/raw
  intersection_distributions:
    no_intersection: 50
    point_intersection: 5
    polygon_intersection: 20
    polyhedron_intersection: 18
    segment_intersection: 7
  num_train_samples: 1000000
  num_val_samples: 100000
  number_of_bins: 10
  skip_processing: true
  transformations: *id002
  volume_range:
  - 1.6667e-07
  - 0.0166666667
  volume_scale_factor: 1000
trainer_config:
  batch_size: 128
  epochs: 20
  fine_tune_data_path: /home/sei/tetrahedron_pair_ML/data/raw/scenes/scene1_two_random_tetrahedra_colliding.csv
  fine_tune_model_path: /home/sei/tetrahedron_pair_ML/artifacts/id0605203440_tetrahedronpairnet_IntersectionStatus_IntersectionVolume_1000000-train_10000-val_vol-0-0.02_epochs-20_adamw-0.001_distributions-no_intersection-43_point_intersection-3_segment_intersection-5_polygon_intersection-22_polyhedron_intersection-27/model.pt
  fine_tune_on: false
  learning_rate: 0.001
  loss_function: IntersectionStatus_IntersectionVolume
  optimizer: adamw
  processed_data_path: data/processed
  skip_training: false
