artifacts_config:
  save_artifacts_to: /home/erendiro/repos/tetrahedron_pair_ML/artifacts
evaluator_config:
  augmentations: &id001
    point_wise_permutation_augmentation_pct: 0
    sort: null
    tetrahedron_wise_permutation_augmentation_pct: 0
    volume_sorting: null
  skip_evaluation: false
  task: regression
  test_data_path: /home/erendiro/repos/tetrahedron_pair_ML/src/evaluator/test_data
  transformations: &id002
    affine_linear_transformation: false
home: /home/erendiro/repos/tetrahedron_pair_ML
model_config:
  activation_function: relu
  architecture:
    deep_set:
      classification_head: []
      num_residual_blocks_per_tet: 1
      num_residual_blocks_post_concat: 1
      regression_head: []
    mlp:
      classification_head: []
      regression_head:
      - 1
      shared_layers:
      - 12
    use: mlp
  dropout_rate: 0.0
  processed_data_path: data/processed
  skip_building: false
  task: regression
  volume_scale_factor: 1
processor_config:
  augmentations: *id001
  dataset_paths:
    processed_data: /home/erendiro/repos/tetrahedron_pair_ML/data/processed
    raw_data: /home/erendiro/repos/tetrahedron_pair_ML/data/raw
  intersection_distributions:
    no_intersection: 0
    point_intersection: 0
    polygon_intersection: 0
    polyhedron_intersection: 100
    segment_intersection: 0
  num_train_samples: 100000
  num_val_samples: 100000
  number_of_bins: 100
  skip_processing: false
  transformations: *id002
  volume_range:
  - 0
  - 0.01
  volume_scale_factor: 1
trainer_config:
  batch_size: 32
  early_stopping_patience: 10
  epochs: 20
  evaluation_metric: accuracy
  learning_rate: 0.001
  learning_rate_schedule: null
  loss_function: regression
  optimizer: adamw
  processed_data_path: data/processed
  skip_training: false
