artifacts_config:
  save_artifacts_to: /home/sei/tetrahedron_pair_ML/artifacts
evaluator_config:
  augmentations: &id001
    point_wise_permutation_augmentation_pct: 0
    sort: null
    tetrahedron_wise_permutation_augmentation_pct: 0
    volume_sorting: null
  model_path: /home/sei/tetrahedron_pair_ML/artifacts/id-20250408-065815_deepset_regression_100000-train_100000-val_vol-0-0.01_epochs-5_adamw-0.001_distributions-polyhedron_intersection-100/model.pt
  skip_evaluation: false
  task: regression
  test_data_path: /home/sei/tetrahedron_pair_ML/src/evaluator/test_data
  transformations: rigid_transformation
home: /home/sei/tetrahedron_pair_ML
model_config:
  architecture:
    deepset:
      classification_head:
      - 12
      - 12
      - 1
      hidden_dim: 12
      num_blocks: 4
      regression_head: []
      shared_layers:
      - 12
    mlp:
      classification_head: []
      regression_head:
      - 12
      - 96
      - 96
      - 96
      - 1
      shared_layers:
      - 12
      - 12
      - 12
      - 12
      - 12
      - 12
    tpnet:
      classification_head: []
      per_tet_layers:
      - 12
      - 12
      - 12
      - 12
      - 12
      - 12
      regression_head:
      - 12
      - 12
      - 1
      shared_layers:
      - 12
      - 12
      - 12
    use_model: tpnet
  common_paramers:
    activation_function: relu
    dropout_rate: 0.0
    task: regression
    volume_scale_factor: 1000000
  processed_data_path: data/processed
  skip_building: false
processor_config:
  augmentations: *id001
  dataset_paths:
    processed_data: /home/sei/tetrahedron_pair_ML/data/processed
    raw_data: /home/sei/tetrahedron_pair_ML/data/raw
  intersection_distributions:
    no_intersection: 0
    point_intersection: 0
    polygon_intersection: 0
    polyhedron_intersection: 100
    segment_intersection: 0
  num_train_samples: 800000
  num_val_samples: 10000
  number_of_bins: 200
  skip_processing: true
  transformations: rigid_transformation
  volume_range:
  - 0
  - 0.01
  volume_scale_factor: 1000000
trainer_config:
  batch_size: 32
  epochs: 10
  learning_rate: 0.0008
  loss_function: regression
  optimizer: adamw
  processed_data_path: data/processed
  skip_training: false
