artifacts_config:
  save_artifacts_to: /home/sei/tetrahedron_pair_ML/artifacts
  storage_level: minimal
evaluator_config:
  augmentations: &id001
    point_wise_permutation_augmentation_pct: 0
    tetrahedron_wise_permutation_augmentation_pct: 0
    x_sorting:
      spatial_based: null
      volume_based: null
    y_sorting:
      difficulty_based: null
  evaluation_n_bins: 10
  model_path: /home/sei/tetrahedron_pair_ML/artifacts/id-20250408-065815_deepset_regression_100000-train_100000-val_vol-0-0.01_epochs-5_adamw-0.001_distributions-polyhedron_intersection-100/model.pt
  regression_consistency_thresholds:
    atol: 0.0001
    rtol: 0.1
  skip_evaluation: false
  task: IntersectionVolume
  test_data_path: /home/sei/tetrahedron_pair_ML/src/evaluator/test_data
  transformations: &id002 []
  volume_range:
  - 0
  - 0.01
  volume_scale_factor: 10000.0
home: /home/sei/tetrahedron_pair_ML
model_config:
  architecture:
    mlp:
      classification_head: []
      regression_head:
      - 128
      - 128
      - 1
      shared_layers:
      - 128
    tetrahedronpairnet:
      classification_head:
      - 16
      - 1
      per_tetrahedron_layers:
      - 64
      - 64
      per_two_tetrahedra_layers:
      - 32
      per_vertex_layers:
      - 48
      - 48
      - 48
      regression_head:
      - 16
      - 1
      shared_layers:
      - 256
      tetrahedra_aggregation_function: max
      vertices_aggregation_function: max
    use_model: mlp
  common_parameters:
    activation_function: relu
    dropout_rate: 0.4
    task: IntersectionVolume
    volume_scale_factor: 10000.0
  processed_data_path: data/processed
  skip_building: false
  task: IntersectionVolume
processor_config:
  augmentations: *id001
  dataset_paths:
    processed_data: /home/sei/tetrahedron_pair_ML/data/processed
    raw_data: /home/sei/tetrahedron_pair_ML/data/raw
  intersection_distributions:
    no_intersection: 0
    point_intersection: 0
    polygon_intersection: 0
    polyhedron_intersection: 100
    segment_intersection: 0
  num_train_samples: 100000
  num_val_samples: 100000
  precision_mode: double
  quality_filtering:
    enabled: false
    min_volume_threshold: 1.66667e-12
  sampling_strategy: log_uniform_volume
  skip_processing: false
  transformations: *id002
  volume_binning:
    max_chunks_without_progress: 100
    n_bins: 100
    stratify_within_bins: false
    volume_range:
    - 1.0e-07
    - 0.02
  volume_scale_factor: 10000.0
trainer_config:
  balance_ratio: 0.5
  batch_size: 32
  epochs: 20
  fine_tune_data_path: /home/sei/tetrahedron_pair_ML/data/raw/scenes/scene1_two_random_tetrahedra_colliding.csv
  fine_tune_model_path: /home/sei/tetrahedron_pair_ML/artifacts/id0605203440_tetrahedronpairnet_IntersectionStatus_IntersectionVolume_1000000-train_10000-val_vol-0-0.02_epochs-20_adamw-0.001_distributions-no_intersection-43_point_intersection-3_segment_intersection-5_polygon_intersection-22_polyhedron_intersection-27/model.pt
  fine_tune_on: false
  learning_rate: 0.001
  loss_function: rmsle
  optimizer: adamw
  processed_data_path: data/processed
  skip_training: false
  task: IntersectionVolume
